--DROP TABLE IF EXISTS USUARIO
CREATE TABLE IF NOT EXISTS USUARIO (        --CRIANDO QUERY - CRIANDO TABELA DE USUARIOS
ID int auto_increment primary key,
NOME varchar(16),
EMAIL varchar(48),
SENHA varchar(10),
NIVEL_ACESSO bit);


--DROP TABLE IF EXISTS DENTISTA
CREATE TABLE IF NOT EXISTS DENTISTA(        --CRIANDO QUERY - CRIANDO TABELA DE DENTISTA
ID int AUTO_INCREMENT primary key,
NOME varchar(255),
SOBRENOME varchar (255),
MATRICULA varchar (255));


--DROP TABLE IF EXISTS PACIENTE
CREATE TABLE IF NOT EXISTS PACIENTE(        --CRIANDO QUERY - CRIANDO TABELA DE PACIENTE
ID int AUTO_INCREMENT primary key,
NOME varchar(255),
SOBRENOME varchar (255),
RG varchar (255),
DATA_NASCIMENTO TIMESTAMP WITH TIME ZONE,
ENDERECO_ID int);


--DROP TABLE IF EXISTS ENDERECO
CREATE TABLE IF NOT EXISTS ENDERECO(        --CRIANDO QUERY - CRIANDO TABELA DE ENDERECO
ID int AUTO_INCREMENT primary key,
RUA varchar(255),
NUMERO varchar (255),
CIDADE varchar (255),
ESTADO varchar (255));

